"""Nested Dict of potentially problematic street names"""

problematic_street_names = {
 '101': {'Northwest Hoyt Street #101'},
 '102': {'Southwest Macadam Avenue #102'},
 '110': {'Southeast Grace Avenue #110'},
 '150': {'Southwest 5th Street #150'},
 '155th': {'Southwest 155th'},
 '156th': {'Southwest 156th'},
 '157th': {'Southwest 157th'},
 '158th': {'Southwest 158th'},
 '160th': {'Southwest 160th'},
 '163rd': {'Southwest 163rd'},
 '165th': {'Southwest 165th'},
 '170': {'South Highway 170'},
 '211': {'South Highway 211', 'Highway 211', 'Southeast Highway 211'},
 '212': {'SE Highway 212', ' Southeast Hwy 212', 'Southeast Highway 212'},
 '213': {'Highway 213', 'South Highway 213'},
 '224': {'Northwest Highway 224',
         'South Highway 224',
         'Southeast Highway 224',
         'Southwest Highway 224'},
 '26': {'Highway 26', 'Southeast Highway 26'},
 '4616': {'4616'},
 '4637': {'4637'},
 '47': {'Northwest Highway 47',
        'Southwest Highway 47',
        'Southwest Old Highway 47'},
 '74th': {'SW 74th'},
 '91st': {'SW 91st'},
 '97055': {'44575 Southeast Kleinsmith Rd.\nSandy, OR 97055'},
 '97266': {'8202 SE Flavel St, Portland, OR 97266'},
 '99': {'Northeast Highway 99'},
 '99E': {'Highway 99E', 'South Highway 99E'},
 '99W': {'North Highway 99W',
         'Northeast Highway 99W',
         'Northeast State Highway 99W',
         'Southwest Old Highway 99W'},
 '99e': {'South Highway 99e'},
 'AVE': {'NE 25th AVE'},
 'Alley': {'North Missouri Ave-Michigan Ave Alley', 'Knapps Alley'},
 'Ankeny': {'SE Ankeny'},
 'Ave': {'12120 SW Imperial Ave',
         '1813 NE 2nd Ave',
         '33rd Ave',
         '4th Ave',
         'Mollala Ave',
         'NE 10th Ave',
         'NE 181st Ave',
         'NE 22nd Ave',
         'NE 33rd Ave',
         'NE 37th Ave',
         'NE 3rd Ave',
         'NE 94th Ave',
         'NE Cumulus Ave',
         'NW 12th Ave',
         'NW 143rd Ave',
         'NW 334th Ave',
         'NW Birdsdale Ave',
         'North 20th Ave',
         'North 26th Ave',
         'North Interstate Ave',
         'Northwest 185th Ave',
         'Pacific Ave',
         'SE 104th Ave',
         'SE 12th Ave',
         'SE 162nd Ave',
         'SE 16th Ave',
         'SE 60th Ave',
         'SE 96th Ave',
         'SE Stratus Ave',
         'SW 11th Ave',
         'SW 125th Ave',
         'SW 78th Ave',
         'SW Martinazzi Ave',
         'Southeast 172nd Ave'},
 'Ave.': {'NE 12th Ave.', 'N. Charleston Ave.', 'NW 21st Ave.', 'SE 21st Ave.'},
 'Blvd.': {'21200 Northwest Rock Creek Blvd.'},
 'Botticelli': {'Botticelli'},
 'Brighton': {'Southwest Brighton'},
 'Burnside': {'West Burnside'},
 'Byway': {'Southwest Kings Byway'},
 'C113': {'Southeast Orient Drive #C113'},
 'Cervantes': {'Cervantes'},
 'Chantilly': {'Southwest Chantilly'},
 'Churchill': {'Southwest Churchill'},
 'Cir': {'SE Enterprise Cir'},
 'Circus': {'Northwest Luray Circus',
            'Southwest Aventine Circus',
            'Southwest Esquiline Circus',
            'Southwest Fairview Circus'},
 'Crescent': {'Northwest Ramsey Crescent'},
 'Crest': {'Collins Crest', 'Southwest Humphrey Park Crest', 'Eagle Crest'},
 'Ct.': {'SW 125th Ct.'},
 'Curve': {'Horseshoe Curve'},
 'Cynthia': {'Southwest Cynthia'},
 'D': {'Northeast 82nd Avenue #D'},
 'Dartmouth': {'E Dartmouth'},
 'Douglas': {'Douglas'},
 'Downs': {'Churchill Downs'},
 'Dr': {'NE Estate Dr',
        'NE Parkway Dr',
        'North Marine Dr',
        'SE Tower Dr',
        'SW Conestoga Dr',
        'SW Cormorant Dr',
        'SW Downing Dr'},
 'Dr.': {'Upper Dr.'},
 'End': {'Northwest Roads End', 'Southeast Roads End'},
 'Falstaff': {'Falstaff'},
 'Fieldcrest': {'Southeast Fieldcrest'},
 'GLN': {'Southwest Malcolm GLN'},
 'Greco': {'El Greco'},
 'Greenway': {'Southwest Greenway'},
 'Grotto': {'The Grotto'},
 'Hassalo': {'NE Hassalo'},
 'Heights': {'Southeast Belmore Heights'},
 'Hotspur': {'Hotspur'},
 'Hwy': {'Columbia River Hwy',
         'Historic Columbia River Hwy',
         'NW Sunset Hwy',
         'SW Hillsboro Hwy',
         'SW Tualatin Valley Hwy'},
 'Jamaica': {'Southwest Jamaica'},
 'Landing': {'Old River Landing', 'Northeast Boones Ferry Landing'},
 'Ln': {'S Rutherford Ln'},
 'Miami': {'Southwest Miami'},
 'Mississippi': {'North Mississippi'},
 'Northbound': {'I5 Freeway Northbound'},
 'Northeast': {'Arney Road Northeast',
               'Donald Road Northeast',
               'Parr Road Northeast'},
 'OR)': {'US 26 (OR)'},
 'Pacific': {'Pacific'},
 'Pericles': {'Pericles'},
 'Pimlico': {'Pimlico'},
 'Pkwy': {'NW Skycrest Pkwy'},
 'Pky': {'NW Skycrest Pky'},
 'Plaza': {'SW Chinook Plaza'},
 'Point': {'Southwest East Lake Point', 'Southwest Cypress Point'},
 'Pointe': {'Cabana Pointe'},
 'Polonius': {'Polonius'},
 'Preakness': {'Southwest Preakness'},
 'Rd': {'NW Cornell Rd',
        'NW Laidlaw Rd',
        'NW Timber Rd',
        'Old Portland Rd',
        'S Carus Rd',
        'SE Foster Rd',
        'SE Sunnyside Rd',
        'SW Bany Rd',
        'SW Bridgeport Rd',
        'SW Brockman Rd',
        'SW Canyon Rd',
        'SW Farmington Rd',
        'SW Nicol Rd',
        'SW Rock Creek Rd',
        'SW Scholls Ferry Rd'},
 'Rd.': {'SW Tonquin Rd.'},
 'Rode': {'Northeast Rode'},
 'Run': {'Fox Run',
         'Pheasant Run',
         'Southwest Gordons Run',
         'Southwest Wheatland Run'},
 'Russell': {'670 North Russell'},
 'Sandy': {'NE Sandy'},
 'Skidmore': {'N Skidmore'},
 'Southbound': {'I5 Freeway Southbound'},
 'Spinosa': {'Spinosa'},
 'Srive': {'North Marine Srive'},
 'St': {'B St',
        'Broadway St',
        'N Front St',
        'N Graham St',
        'NE Broadway St',
        'NE Broadways St',
        'NE Evans St',
        'NE First St',
        'NE Lenox St',
        'NE Lincoln St',
        'NE Multnomah St',
        'NE Shaver St',
        'NW Darnielle St',
        'NW Pettygrove St',
        'North Prescott St',
        'Northeast Lincoln St',
        'Northwest Birch St',
        'SE Ankeny St',
        'SE DIvision St',
        'SE Division St',
        'SE Oak St',
        'SE Stark St',
        'SW 5th St',
        'SW Adams St',
        'SW Comust St',
        'SW Inglewood St',
        'SW Jefferson St',
        'Southeast Lois St',
        'Z St'},
 'St.': {'N Lombard St.',
         'N. Lombard St.',
         'NE Everett St.',
         'NE Glisan St.',
         'NW 18th St.',
         'NW Raleigh St.',
         'North Lombard St.'},
 'Strand': {'The Strand'},
 'Summac': {'Southwest Summac'},
 'Summit': {'Nansen Summit', 'Oswego Summit'},
 'TRL': {'Southeast Hittay TRL'},
 'Taylor': {'SW Taylor'},
 'Terre': {'Southeast La Bonne Terre'},
 'Touchstone': {'Touchstone'},
 'Vista': {'Northeast Dutch Vista'},
 'Walk': {"Nature'S Walk"},
 'Wheatherstone': {'Wheatherstone'},
 'Wheatland': {'Southwest Wheatland'},
 'Willamina': {'Willamina'},
 'Woods': {'Summer Woods', 'Trillium Woods'},
 'st.': {'N. Lombard st.', 'North Harborgate st.'},
 'street': {'Main street'},
 'unknown': {'unknown'}}